// Fun Fact: I drink a looot of water.
// Twitter: @mikeeowino
print(" *                *            * ")
print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")

// Mike Owino
print("  SSS   L     ")
print(" S   S  L     ")
print(" S      L     ")
print("  SSS   L     ")
print("     S  L     ")
print(" S   S  L     ")
print("  SSS   LLLLL ")